In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
!pip install mlflow

In [3]:
import mlflow

In [4]:
mlflow.set_tracking_uri("sqlite:///mlflow.db")

In [5]:
mlflow.set_experiment("HousePricePrediction")

2026/05/28 10:29:09 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/05/28 10:29:09 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.


<Experiment: artifact_location='/workspaces/mlops_sample/mlruns/1', creation_time=1779784903294, experiment_id='1', last_update_time=1779784903294, lifecycle_stage='active', name='HousePricePrediction', tags={'mlflow.sharedViewState.cd6101a9360b29aef84135a7315deede6de435fed32ccc466404e44adf9fede2': 'deflate;eJzFVE1v2zAM/SuFzsEQO07s5JZmbVcsGYakKwYUhStLdCJUljxJ7uIV+e+j7Hy47YZdBvQoiuQj3yP5TCxQwzaXQjowZEJIj2jDwZzXn6HGN3XOiKxyYD9YR41LnSjg5DS1jExyKi30SPN/478nZDqfo5MUObCaSTimnzInnnw8p45acPbwc3ffI4XmIG/BWKHVKULKs2WlLMZYkMAc8JmWVYGWyV23vIeVrgyDB3TsWhc+qX1t/djCe3MBaGZoM4VtoktqaIFvicwoodapoe7FR0G3KYfSbbpGlYJFbqjTpkFzdO1dPfoDweYM9nCxLaniwMnkmYwDHmYcYk7zYcQinsSjcAzjMMtyHg0GAZk4UyGrg3ycJzDijFEeZSzPaBLFwxBimgRR1h/t6d+1CF+FUj7/3R7xk+Ac1Ol9K6zIhBSuXtASy9h13TxVyPjl9XJ1kwb9dPntywo7YbrAJgFFmG1QYc/7M6kqgTAkiONxnCTJIBn0o3DztK23qvLd16VPdT5dkhZhpivlbvSszUUmQf/A/Ao1RcGvD+miKAz78SCKK54ok0PppwWVd76v/agJewUKvC78wFObrB3aDKVIhfMOmJnseq/qjcajfhgGoyjj65zxd6/XhKllGmFeVXpMbR/V8BHG6/evFHeE7O67Q7FHeTMWf0JTtLkOzU6e7RfPFyF

In [5]:
data = pd.read_csv('House Price Prediction Dataset.csv')

In [6]:
data.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056


In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Id         2000 non-null   int64 
 1   Area       2000 non-null   int64 
 2   Bedrooms   2000 non-null   int64 
 3   Bathrooms  2000 non-null   int64 
 4   Floors     2000 non-null   int64 
 5   YearBuilt  2000 non-null   int64 
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64 
dtypes: int64(7), object(3)
memory usage: 156.4+ KB


In [11]:
data.describe()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000


In [12]:
data['Location'].unique()

array(['Downtown', 'Suburban', 'Urban', 'Rural'], dtype=object)

In [13]:
data['Condition'].unique()

array(['Excellent', 'Good', 'Fair', 'Poor'], dtype=object)

In [14]:
data['Garage'].unique()

array(['No', 'Yes'], dtype=object)

In [7]:
final_df  = pd.get_dummies(data = data,drop_first=True, columns=['Location', 'Condition', 'Garage'], dtype='int')

In [16]:
final_df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price,Location_Rural,Location_Suburban,Location_Urban,Condition_Fair,Condition_Good,Condition_Poor,Garage_Yes
0,1,1360,5,4,3,1970,149919,0,0,0,0,0,0,0
1,2,4272,5,4,3,1958,424998,0,0,0,0,0,0,0
2,3,3592,2,2,3,1938,266746,0,0,0,0,1,0,0
3,4,966,4,2,2,1902,244020,0,1,0,1,0,0,1
4,5,4926,1,4,2,1975,636056,0,0,0,1,0,0,1


In [17]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score

In [18]:
features = final_df[final_df.columns.drop(['Id','Price', 'YearBuilt'])].values

In [19]:
target = final_df['Price'].values

In [20]:
features

array([[1360,    5,    4, ...,    0,    0,    0],
       [4272,    5,    4, ...,    0,    0,    0],
       [3592,    2,    2, ...,    1,    0,    0],
       ...,
       [1062,    5,    1, ...,    0,    1,    0],
       [4062,    3,    1, ...,    0,    0,    1],
       [2989,    5,    1, ...,    0,    0,    0]])

In [21]:
target

array([149919, 424998, 266746, ..., 476925, 161119, 482525])

In [22]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.20, random_state=42)

In [23]:
training_data_path = final_df.to_csv('cleaned_data.csv')

# Running Different Models

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [26]:
##  Multiple Linear Regression

In [27]:
# with mlflow.start_run():
#     mlflow.set_tag("developer", "Praveen")
#     mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
#     linear_reg = LinearRegression()
#     linear_reg.fit(X_train, y_train)
#     y_prediction = linear_reg.predict(X_test)
#     rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
#     r2_score = r2_score(y_true=y_test, y_pred=y_prediction)
#     mlflow.log_metric("rmse", rmse)
#     mlflow.log_metric("r2_score", r2_score)

In [28]:
# with mlflow.start_run(run_name="Polynomial Regression"):
#     mlflow.set_tag("developer", "Praveen")
#     mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
#     mlflow.log_param("algorithm", "Polynomial Function")
#     mlflow.log_param("polynomial_degree", "4")
#     poly = PolynomialFeatures(degree=4, include_bias=False)
#     X_poly = poly.fit_transform(X_train)
#     model = LinearRegression()
#     model.fit(X_poly, y_train)
#     y_prediction = model.predict(poly.fit_transform(X_test))
#     rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
#     mlflow.log_metric("rmse", rmse)

In [29]:
!pip install xgboost

In [30]:
from xgboost import XGBRegressor

In [31]:
xgb = XGBRegressor()

In [32]:
# with mlflow.start_run(run_name="XGB Regressor default"):
#     mlflow.set_tag("developer", "Praveen")
#     mlflow.log_param("algorithm", "XGB Regressor with default Params")
#     mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
#     xgb.fit(X_train, y_train)
#     y_prediction = xgb.predict(X_test)
#     rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
#     mlflow.log_metric("rmse", rmse)

In [33]:
# !pip install hyperopt

In [34]:
# from hyperopt import fmin, tpe, hp, STATUS_OK, Trials

In [35]:
# k = 5
# print(f'thenumber is {k}')

In [36]:
import xgboost as xgb

In [37]:
# # 1. Define the search space
# space = {
#     'max_depth': hp.quniform('max_depth', 3, 10, 1),
#     'learning_rate': hp.loguniform('learning_rate', -3, 0),
#     'n_estimators': hp.quniform('n_estimators', 100, 1000, 10),
#     'reg_alpha': hp.uniform('reg_alpha', 0, 1),
#     'reg_lambda': hp.uniform('reg_lambda', 0, 1)
# }


# # 2. Define the objective function

# def objective(params):
#     # Convert parameters to correct types (Hyperopt often returns floats)
#     params['max_depth'] = int(params['max_depth'])
#     params['n_estimators'] = int(params['n_estimators'])
    
#     with mlflow.start_run(nested=True):
#         mlflow.set_tag("model", "xgboost")
#         model = xgb.XGBRegressor(**params, early_stopping_rounds=10, random_state=42)
#         model.fit(X_train, y_train, eval_set=[(X_test, y_test)])
#         preds = model.predict(X_test)
#         rmse = mean_squared_error(y_test, preds, squared=False)
#         actual_trees = model.best_iteration if hasattr(model, 'best_iteration') else params['n_estimators']

# # Log to MLflow
#         mlflow.log_params(params)
#         mlflow.log_metric("rmse", rmse)
#         mlflow.log_metric("best_iteration", actual_trees)
        
#         return {'loss': rmse, 'status': STATUS_OK}


# with mlflow.start_run(run_name="XGB_Hyperopt_Optimization"):
#     best_params = fmin(fn = objective, space = space, algo = tpe.suggest, max_evals = 50, trials = Trials())
#     mlflow.log_params(best_params)

In [39]:
mlflow.autolog()

with mlflow.start_run(run_name="New XGB Regressor autolog"):
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("algorithm", "New XGB Regressor with Autolog Params")
    mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
    autolog_model = xgb.XGBRegressor(n_estimators = 810, learning_rate = 0.11014099849219953, max_depth = 4, reg_alpha = 0.9493672374210916, reg_lambda = 0.6839771610567229)
    autolog_model.fit(X_train, y_train)
    y_prediction = autolog_model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
    mlflow.log_metric("rmse", rmse)
    mlflow.log_artifact(local_path="/workspaces/mlops_sample/models", artifact_path="models/")

2026/05/27 09:48:03 WARNING mlflow.utils.autologging_utils: MLflow sklearn autologging is known to be compatible with 1.3.0 <= scikit-learn <= 1.7.0, but the installed version is 1.0.2. If you encounter errors during autologging, try upgrading / downgrading scikit-learn to a compatible version, or try upgrading MLflow.
2026/05/27 09:48:04 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2026/05/27 09:48:04 WARNING mlflow.utils.autologging_utils: MLflow statsmodels autologging is known to be compatible with 0.14.1 <= statsmodels <= 0.14.4, but the installed version is 0.13.2. If you encounter errors during autologging, try upgrading / downgrading statsmodels to a compatible version, or try upgrading MLflow.
2026/05/27 09:48:08 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2026/05/27 09:48:08 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2026/05/27 09:48:10 WARNING mlflow.models.model: `artifact_path`

In [41]:
mlflow.autolog()

with mlflow.start_run(run_name="New XGB model"):
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("algorithm", "New XGB Regressor with Autolog Params")
    best_params = {
        'n_estimators':810,
        'learning_rate':0.11014099849219953,
        'max_depth':4,
        'reg_alpha':0.9493672374210916,
        'reg_lambda':0.6839771610567229    
    }
    
    
    mlflow.log_params(best_params)
    mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
    autolog_model = xgb.XGBRegressor(n_estimators = 810, learning_rate = 0.11014099849219953, max_depth = 4, reg_alpha = 0.9493672374210916, reg_lambda = 0.6839771610567229)
    autolog_model.fit(X_train, y_train)
    y_prediction = autolog_model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
    mlflow.log_metric("rmse", rmse)
    mlflow.xgboost.log_model(xgb_model=autolog_model, artifact_path="new_model")

2026/05/27 10:18:59 WARNING mlflow.utils.autologging_utils: MLflow sklearn autologging is known to be compatible with 1.3.0 <= scikit-learn <= 1.7.0, but the installed version is 1.0.2. If you encounter errors during autologging, try upgrading / downgrading scikit-learn to a compatible version, or try upgrading MLflow.
2026/05/27 10:18:59 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2026/05/27 10:18:59 WARNING mlflow.utils.autologging_utils: MLflow statsmodels autologging is known to be compatible with 0.14.1 <= statsmodels <= 0.14.4, but the installed version is 0.13.2. If you encounter errors during autologging, try upgrading / downgrading statsmodels to a compatible version, or try upgrading MLflow.
2026/05/27 10:18:59 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2026/05/27 10:18:59 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2026/05/27 10:18:59 WARNING mlflow.models.model: `artifact_path`

In [43]:
run_id = "e5841658e52c49538a30613ef1f46e2f"
model_path = "new_model" # The default name used in log_model(model, "model")

# 2. Construct the URI
model_uri = f"runs:/{run_id}/{model_path}"

# 3. Load the model
# Use pyfunc for a generic python object or flavor-specific (e.g., mlflow.sklearn)
loaded_model = mlflow.pyfunc.load_model(model_uri)

In [45]:
X_test[[0]]

array([[633,   1,   4,   2,   0,   0,   1,   1,   0,   0,   0]])

In [46]:
y_test[0]

514764

In [47]:
# 4. Use for predictions
predictions = loaded_model.predict(X_test[[0]])

In [48]:
predictions

array([639061.9], dtype=float32)

In [57]:
mlflow.version.VERSION

'3.1.4'

In [8]:
###Registering the models in the mlflow registry

In [6]:
from mlflow.tracking import MlflowClient

In [9]:
MLFLOW_TRACKING_URI  = "sqlite:///mlflow.db"

In [10]:
client = MlflowClient(tracking_uri=MLFLOW_TRACKING_URI)

In [15]:
experiments = client.search_experiments()

for exp in experiments:
    print(f"Name: {exp.name}, ID: {exp.experiment_id}, Location: {exp.artifact_location}")

Name: HousePricePrediction, ID: 1, Location: /workspaces/mlops_sample/mlruns/1
Name: Default, ID: 0, Location: mlflow-artifacts:/0


In [16]:
client.search_runs(experiment_ids=['1'], filter_string = "metrics.rmse > 332014.00", run_view_type=1, max_results=5)

[<Run: data=<RunData: metrics={'rmse': 332014.73664794414}, params={'algorithm': 'New XGB Regressor with Autolog Params',
  'base_score': 'None',
  'booster': 'None',
  'colsample_bylevel': 'None',
  'colsample_bynode': 'None',
  'colsample_bytree': 'None',
  'custom_metric': 'None',
  'data': '/workspaces/mlops_sample/cleaned_data.csv',
  'device': 'None',
  'early_stopping_rounds': 'None',
  'eval_metric': 'None',
  'gamma': 'None',
  'grow_policy': 'None',
  'interaction_constraints': 'None',
  'learning_rate': '0.11014099849219953',
  'max_bin': 'None',
  'max_cat_threshold': 'None',
  'max_cat_to_onehot': 'None',
  'max_delta_step': 'None',
  'max_depth': '4',
  'max_leaves': 'None',
  'maximize': 'None',
  'min_child_weight': 'None',
  'monotone_constraints': 'None',
  'multi_strategy': 'None',
  'n_estimators': '810',
  'n_jobs': 'None',
  'num_boost_round': '810',
  'num_parallel_tree': 'None',
  'objective': 'reg:squarederror',
  'random_state': 'None',
  'reg_alpha': '0.94936

In [17]:
## Registering a model

In [31]:
# model_path = artifacts
XGB_MODEL_URI = "runs:/e5841658e52c49538a30613ef1f46e2f/model"

In [32]:
mlflow.register_model(model_uri = XGB_MODEL_URI, name="HousePrice-Predictor")

Registered model 'HousePrice-Predictor' already exists. Creating a new version of this model...
2026/05/28 11:15:02 WARNING mlflow.tracking._model_registry.fluent: Run with id e5841658e52c49538a30613ef1f46e2f has no artifacts at artifact path 'model', registering model based on models:/m-e4a47968500d4c3089c7a91458fe9434 instead
Created version '3' of model 'HousePrice-Predictor'.


<ModelVersion: aliases=[], creation_timestamp=1779966902987, current_stage='None', deployment_job_state=None, description=None, last_updated_timestamp=1779966902987, metrics=None, model_id=None, name='HousePrice-Predictor', params=None, run_id='e5841658e52c49538a30613ef1f46e2f', run_link=None, source='models:/m-e4a47968500d4c3089c7a91458fe9434', status='READY', status_message=None, tags={}, user_id=None, version=3>

In [30]:
import mlflow.xgboost

# Correct way to format the URI
model_uri = "runs:/e5841658e52c49538a30613ef1f46e2f/model" 
loaded_model = mlflow.xgboost.load_model(model_uri)

In [39]:
registered_models = mlflow.search_registered_models()
for model in registered_models:
    print(f"Model Name: {model.name}")

Model Name: HousePrice-Predictor


In [44]:
for versions in client.get_latest_versions(name = "HousePrice-Predictor"):
    print(f"version:{versions.version}, stage: {versions.current_stage}")

version:3, stage: None
version:2, stage: Staging


/tmp/ipykernel_8129/2968444727.py:1: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  for versions in client.get_latest_versions(name = "HousePrice-Predictor"):


In [47]:
client.transition_model_version_stage(name= 'HousePrice-Predictor', version=3, stage='Production')

/tmp/ipykernel_8129/139806900.py:1: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(name= 'HousePrice-Predictor', version=3, stage='Production')


<ModelVersion: aliases=[], creation_timestamp=1779966902987, current_stage='Production', deployment_job_state=None, description='New XGB Model', last_updated_timestamp=1779969909691, metrics=None, model_id=None, name='HousePrice-Predictor', params=None, run_id='e5841658e52c49538a30613ef1f46e2f', run_link=None, source='models:/m-e4a47968500d4c3089c7a91458fe9434', status='READY', status_message=None, tags={'algorithm': 'new-xgb', 'rmse': '332014.73664794414'}, user_id=None, version=3>

In [48]:
## Checking the staged and production models performance 

In [ ]:
version3_model_uri = "runs:/e5841658e52c49538a30613ef1f46e2f/model"
version2_model_uri = "runs:/e5841658e52c49538a30613ef1f46e2f/model"