In [1]:
import argparse
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import datetime
from xgboost import XGBRegressor

In [2]:
data_source = 'Real estate.csv'

In [10]:
dataset = pd.read_csv(data_source)
Features = ['X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores', 'X5 latitude', 'X6 longitude']
target = ['Y house price of unit area']
X_train, X_test, y_train, y_test = train_test_split(dataset[Features], dataset[target], test_size=0.10, random_state=42)
print("Stage 1: Data Processing Completed Successfully" + "\u2705")

Stage 1: Data Processing Completed Successfully✅


In [11]:
RF_model = RandomForestRegressor()
RF_model.fit(X_train, y_train)
predictions = RF_model.predict(X_test)
RMSE_score_value = np.sqrt(mean_squared_error(y_true=y_test, y_pred=predictions))
R2_score_value = r2_score(y_true=y_test, y_pred=predictions)
print(f'RMSE_score_value: {RMSE_score_value}')
print(f'R2_score_value: {R2_score_value}')

RMSE_score_value: 6.849343958766601
R2_score_value: 0.76063069381841


In [12]:
import joblib

In [14]:
# Save the trained model to a file
joblib.dump(RF_model, 'RandomForestRegressor_model.bin')

['RandomForestRegressor_model.bin']

In [23]:
#Predicting using saved model
saved_model = joblib.load('RandomForestRegressor_model.bin')
saved_model.predict(X_test.values[[0]])

array([50.41207403])

In [20]:
X_test.values[[0]]

array([[  1.1    , 193.5845 ,   6.     ,  24.96571, 121.54089]])

In [21]:
y_test.values[[0]]

array([[45.1]])

In [26]:
import platform
print(platform.python_version())

3.9.12


In [29]:

print(scikit-learn.__version__)

NameError: name 'scikit' is not defined